name: Test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
    - name: Check out main branch code
      if: github.event_name != 'pull_request_target'
      uses: actions/checkout@v3

    - name: Check out PR branch code
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Verify no uncommitted changes from make lint
      run: |
        git init
        git add .
        make lint

        if [ -n "$GEN_DIFF" ]; then
            echo '"make lint" resulted in changes not in git' 1>&2
            git status
            exit 1
        fi
    
    - name: run tests
      run: |
        make test

    - name: make build
      run: |
        make build
